/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bt.lab5;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Kien Luu
 */
public class Bai2 extends javax.swing.JFrame {
    ArrayList<Student> list = new ArrayList<>();
    int current = 0;
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QLSINHVIEN;user=sa;password=Kientung789;encrypt=true;trustServerCertificate=true;";

    /**
     * Creates new form Bai2
     */
    public Bai2() {
        initComponents();
        LoadToArray();
        Display(current);
    }
    
    public void LoadToArray() {
        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=QLSINHVIEN;user=sa;password=Kientung789;encrypt=true;trustServerCertificate=true;";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection(url);
            String sql = "select * from Students";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            list.clear();
            while(rs.next()) {
                String masv = rs.getString(1);
                String hoTen = rs.getString(2);
                String mail = rs.getString(3);
                String sdt = rs.getString(4);
                String diaChi = rs.getString(6);
                boolean gioiTinh = rs.getBoolean(5);
                Student sv = new Student(masv, hoTen, mail, sdt, diaChi, gioiTinh);
                list.add(sv);
           }
        } catch (Exception e) {
            e.getMessage();
        }
    }

    public void clear() {
        txtHoten.setText("");
        txtMaSV.setText("");
        txtMail.setText("");
        txtPhone.setText("");
        txtDiachi.setText("");
        rdNam.setSelected(true);
    }
    
    public void Display(int i) {
        String ten = list.get(i).hoTen;
        String ma = list.get(i).masv;
        String mail = list.get(i).mail;
        String phone = list.get(i).sdt;
        String diachi = list.get(i).diaChi;
        Boolean gender = list.get(i).gioiTinh;
        txtHoten.setText(ten);
        txtMaSV.setText(ma);
        txtMail.setText(mail);
        txtPhone.setText(phone);
        txtDiachi.setText(diachi);
        if (gender == true) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiachi = new javax.swing.JTextArea();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        btnLastLeft = new javax.swing.JButton();
        btnPrevius = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLastRight = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Quản Lý Users");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Giới tính:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã SV:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số ĐT:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        btnGroupGender.add(rdNam);
        rdNam.setText("Nam");

        btnGroupGender.add(rdNu);
        rdNu.setText("Nữ");

        txtDiachi.setColumns(20);
        txtDiachi.setRows(5);
        jScrollPane1.setViewportView(txtDiachi);

        Add.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\Add.png")); // NOI18N
        Add.setText("Add");
        Add.setMaximumSize(new java.awt.Dimension(150, 23));
        Add.setMinimumSize(new java.awt.Dimension(150, 25));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\Delete.png")); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Save.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\Save.png")); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Update.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\Edit.png")); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        btnLastLeft.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\MaxLeft.png")); // NOI18N
        btnLastLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastLeftActionPerformed(evt);
            }
        });

        btnPrevius.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\TwoLeft.png")); // NOI18N
        btnPrevius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviusActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\TwoRight.png")); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLastRight.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\MaxRight.png")); // NOI18N
        btnLastRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastRightActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon("F:\\Java Lab3\\img_button\\find16px.png")); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdNam)
                                .addGap(31, 31, 31)
                                .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaSV)
                                    .addComponent(txtHoten)
                                    .addComponent(txtMail)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnLastLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrevius, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLastRight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Delete)
                        .addGap(18, 18, 18)
                        .addComponent(Update)
                        .addGap(18, 18, 18)
                        .addComponent(Save))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdNam)
                            .addComponent(rdNu))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLastRight)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext)
                        .addComponent(btnPrevius)
                        .addComponent(btnLastLeft)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void btnLastLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastLeftActionPerformed
        current = 0;
        Display(current);
    }//GEN-LAST:event_btnLastLeftActionPerformed
    
    
    private void btnLastRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastRightActionPerformed
        current = list.size() - 1;
        Display(current);
    }//GEN-LAST:event_btnLastRightActionPerformed

    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (current < list.size() - 1) {
            current += 1;
            Display(current);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    
    private void btnPreviusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviusActionPerformed
      if (current > 0) {
            current -= 1;
            Display(current);
        }
    }//GEN-LAST:event_btnPreviusActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        clear();
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if (txtMaSV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập mã sinh viên");
            txtMaSV.requestFocus();
            return;
        }
        try {
            System.out.println(txtMaSV.getText());
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection(url);
            String sql = "delete from STUDENTS where MaSV = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, txtMaSV.getText());
            st.execute();
            JOptionPane.showMessageDialog(this, "Delete Thành công!");
            conn.close();
            current --;
            Display(current);
            LoadToArray();
        } catch (Exception e) {
            e.getMessage();
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Boolean exist = false;
        String masv = txtMaSV.getText();
        
        if (masv.equals("")) {
           JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
           txtMaSV.requestFocus();
           return;
        }
        
        for (Student sv : list) {
            if (masv.equals(sv.masv)) {
                exist = true;
                break;
            }
        }
        
        if (exist != false) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection(url);
                String sql = "update STUDENTS set MASV = ?, HOTEN = ?, EMAIL = ?, SODT = ?, GIOITINH = ?, DIACHI= ? where MaSV = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txtMaSV.getText());
                st.setString(2, txtHoten.getText());
                st.setString(3, txtMail.getText());
                st.setString(4, txtPhone.getText());
                boolean gender = rdNam.isSelected();
                st.setBoolean(5, gender);
                st.setString(6, txtDiachi.getText());
                st.setString(7, txtMaSV.getText());
                st.execute();
                JOptionPane.showMessageDialog(this, "Update Thành công!");
                conn.close();
                LoadToArray();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } 
        } else {
            JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
        }   
    }//GEN-LAST:event_UpdateActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Boolean exist = false;
        String masv = txtMaSV.getText();
        
        if (masv.equals("")) {
           JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
           txtMaSV.requestFocus();
           return;
        }
        
        for (Student sv : list) {
            if (masv.equals(sv.masv)) {
                exist = true;
                break;
            }
        }
        
         if (exist == false) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection(url);
                String sql = "Insert into STUDENTS values (?, ?, ?, ?, ?, ?)";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txtMaSV.getText());
                st.setString(2, txtHoten.getText());
                st.setString(3, txtMail.getText());
                st.setString(4, txtPhone.getText());
                boolean gender = rdNam.isSelected();
                st.setBoolean(5, gender);
                st.setString(6, txtDiachi.getText());
                st.execute();
                JOptionPane.showMessageDialog(this, "Thêm Thành công!");
                conn.close();
                LoadToArray();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } 
        } else {
            JOptionPane.showMessageDialog(this, "Mã sinh viên đã tồn tại");
        }   
    }//GEN-LAST:event_SaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String masv = txtMaSV.getText();
        
        if (masv.equals("")) {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên");
           txtMaSV.requestFocus();
           return;
        }
        
        for (int i = 0; i <= list.size(); i++) {
            if (i == list.size()) {
                JOptionPane.showMessageDialog(this, "Không tồn tại sinh viên");
            } else if (masv.equals(list.get(i).masv)) {
                Display(i);
                break;
            }
            System.out.println(i);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Save;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnLastLeft;
    private javax.swing.JButton btnLastRight;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevius;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTextArea txtDiachi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
