CREATE DATABASE QLSACH
GO

CREATE TABLE BOOK (
	ID INT,
	TITLE NVARCHAR(50),
	PRICE FLOAT
);

INSERT INTO BOOK VALUES (1, 'CLEAN CODE', 120)
INSERT INTO BOOK VALUES (2, 'CLEAN CODE 1', 120)
INSERT INTO BOOK VALUES (3, 'CLEAN CODE 2', 120)